modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"
issueTrackerURL = "https://github.com/MikhailTapio/Paimon/issues"
[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "${mod_authors}"
description = '''${mod_description}'''
[[dependencies.${ mod_id }]]
modId = "curios"
mandatory = true
versionRange = "*"
ordering = "AFTER"
side = "BOTH"